"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const miniBodegas_1 = require("../controllers/miniBodegas");
const express_1 = require("express");
exports.miniBodegas_router = express_1.Router();
exports.miniBodegas_router.post('/miniBodegas/crear', miniBodegas_1.miniBodegas_controller.create);
exports.miniBodegas_router.get('/miniBodegas/traertodos', miniBodegas_1.miniBodegas_controller.getAll);
exports.miniBodegas_router.get('/miniBodegas/nombreId', miniBodegas_1.miniBodegas_controller.getAllNameandID);
exports.miniBodegas_router.get('/miniBodegas/:id', miniBodegas_1.miniBodegas_controller.getMinibodegabyId);
exports.miniBodegas_router.get('/miniBodegas/getOne/:id', miniBodegas_1.miniBodegas_controller.getOne);
exports.miniBodegas_router.get('/miniBodegas/getByUsuId/:id', miniBodegas_1.miniBodegas_controller.getMinibodegabyUsuId);
exports.miniBodegas_router.post('/miniBodegas/actualizar', miniBodegas_1.miniBodegas_controller.UpdateById);
